##################################################################################################
#                                                                                                #
#                     ___                                        ___                             #
#                    (   )                                      (   )       .-.                  #
#            .--.     | |_       .---.   ___ .-.        .--.     | | .-.   ( __)    .-..         #
#          /  _  \   (   __)    / .-, \ (   )   \     /  _  \    | |/   \  (''")   /    \        #
#         . .' `. ;   | |      (__) ; |  | ' .-. ;   . .' `. ;   |  .-. .   | |   ' .-,  ;       #
#         | '   | |   | | ___    .'`  |  |  / (___)  | '   | |   | |  | |   | |   | |  . |       #
#         _\_`.(___)  | |(   )  / .'| |  | |         _\_`.(___)  | |  | |   | |   | |  | |       #
#        (   ). '.    | | | |  | /  | |  | |        (   ). '.    | |  | |   | |   | |  | |       #
#         | |  `\ |   | ' | |  ; |  ; |  | |         | |  `\ |   | |  | |   | |   | |  ' |       #
#         ; '._,' '   ' `-' ;  ' `-'  |  | |         ; '._,' '   | |  | |   | |   | `-'  '       #
#          '.___.'     `.__.   `.__.'_. (___)         '.___.'   (___)(___) (___)  | \__.'        #
#                                                                                 | |            #
#                                                                                (___)           #
#                                                                                                #
##################################################################################################

# Sets user-defined palette
palette = "sandchocolate"

[character]
success_symbol = "[[󱢠](green) ❯](cyan)"
error_symbol = "[[󰴔](magenta) ❯](red)"
vimcmd_symbol = "[[󰛠](yellow) ❮](green)"

[directory]
truncation_length = 4
style = "bold blue"

[palettes.sandchocolate]
red = "#bf7c73"
orange = "#bf9873"
yellow = "#bfb373"
limeyellow = "#adbf73"
green = "#8dbf73"
limegreen = "#73bf7e"
cyan = "#73bfae"
lightblue = "#7395bf"
blue = "#8873bf"
purple = "#b673bf"
magenta = "#bf73a7"
pink = "#bf7388"

text = "#edc9af"
subtext1 = "#d5b59e"
subtext2 = "#bea18c"
overlay2 = "#a68d7b"
overlay1 = "#8e7969"
overlay0 = "#776558"
surface2 = "#5f5046"
surface1 = "#4c4a45"
surface0 = "#2f2823"
base = "#181412"
mantle = "#100d0c"
crust = "#080706"
